import Head from 'next/head';
import Image from 'next/image';
import Script from 'next/script';

import Container from '../components/Container/Container';
import Header from '../components/Header';
import Button from '../components/Button/Button';

import styles from '../styles/Home.module.scss';
import products from '../data/products.json';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Container>
          <h1>Hyper Bros. Trading Company</h1>
          <h2>Available Cards</h2>
          <ul className={styles.cards}>
            {products.map((product) => (
              <li key={product.id}>
                <Image
                  priority="true"
                  width="864"
                  height="1200"
                  src={product.image}
                  alt={product.title}
                />
                <h3 className={styles.productTitle}>{product.title}</h3>
                <p className={styles.productPrice}>${product.price}</p>
                <p>
                  <Button
                    styleName="snipcart-add-item"
                    data-item-id={product.id}
                    data-item-price={product.price}
                    data-item-url="/"
                    data-item-description=""
                    data-item-image={product.image}
                    data-item-name={product.title}
                  >
                    Add to Cart
                  </Button>
                </p>
              </li>
            ))}
          </ul>
        </Container>
      </main>

      <footer className={styles.footer}>
        &copy; {new Date().getFullYear()} Hyper Bros. Trading Cards
      </footer>
    </div>
  );
}
